version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    entrypoint: wait-for db:3306 -t 40 -- sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db  
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
